version: '2'

services:
  app:
    build: .
    image: siffra/android-quasar-cordova
    command: sh
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 8087:8080
    tty: true
